### ISSUE TITLE
django-stubs 4.2.7 throws type check error for `Group.user_set`

### ISSUE THREAD

**Issue by johnthagen** [typeddjango/django-stubs#1862]
# Bug report

With `django-stubs` 4.2.6, the following simplified code type checked:

```py
from django.contrib.auth.models import Group, User

group = Group()
group.user_set.add(User(username=""))
```

But with with 4.2.7:

```
$ mypy main.py 
main.py:4: error: "Group" has no attribute "user_set"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```

## How is that should be

I expect no type check error here. This seems to be a common way to get the `User`s of a `Group`:

- https://stackoverflow.com/a/58453760
- https://snakeycode.wordpress.com/2015/03/11/django-get-all-the-users-in-a-group/
- http://digitaldreamer.net/blog/2010/5/10/get-all-users-group-django/

## System information

- OS: macOS
- `python` version: 3.10.13
- `django` version: 4.2.8
- `mypy` version: 1.7.1
- `django-stubs` version: 4.2.7
- `django-stubs-ext` version: 4.2.7

### Configuration

```toml
[tool.mypy]
ignore_missing_imports = true
strict = true
disallow_subclassing_any = false
disallow_untyped_decorators = false
warn_return_any = false

plugins = [
    "pydantic.mypy",
    "mypy_django_plugin.main",
]

[tool.django-stubs]
django_settings_module = "config.settings"
```
