### ISSUE TITLE
Incompatible with mypy 1.12.0 due to "compatible-mypy": ["mypy~=1.11.0"]

### ISSUE THREAD

**Issue by ssbarnea** [typeddjango/django-stubs#2404]
# Bug report

It seems that the `compatible-mypy` is preventing users from using mypy 1.12.0, causing either installations failures or conflicts.

## How is that should be

Update it to allow newer version of mypy once it is updated, ideally it should be a range, or just `>=`.

This problem is also enhanced for mypy users of pre-commit, which would have a configuration like:

```yaml
  - repo: https://github.com/pre-commit/mirrors-mypy.git
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - django-stubs[compatible-mypy]
```

The mypy release version is updated automatically with new pull-requests, but as you can see the `compatible-mypy` extra would cause the hook to fail to install with newer versions.
