### ISSUE TITLE
No module named 'mypy_django_plugin'

### ISSUE THREAD

**Issue by revmischa** [typeddjango/django-stubs#518]
# Bug report

## What's wrong

I can `runserver` without any problems. I just can't run `mypy`.

```
[mypy]
plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = myapp.settings.local
```

```
Error importing plugin 'mypy_django_plugin.main': No module named 'mypy_django_plugin'
```

## System information

- OS:
- `python` version: 3.9
- `django` version: 3.1.1
- `mypy` version: 0.790
- `django-stubs` version: 1.7.0

**Comment by sobolevn** [comment]
Do you have `django-stubs` installed? Can you run `python -c 'from mypy_django_plugin import main'`?

**Comment by revmischa** [comment]
I do, running that command does not raise any import error

**Comment by revmischa** [comment]
No error running `python -m mypy_django_plugin.main` either

**Comment by sobolevn** [comment]
Are `mypy` and `django-stubs` in the same `venv`?

**Comment by revmischa** [comment]
Yep. Using poetry.

**Comment by sobolevn** [comment]
Then, I would love to see a sample reproduction repo. 
Because, it works for me and the CI says it is working. 

So, no ideas how to reproduce and fix it 😞

**Comment by ghost** [comment]
does anything change if you explicitly specify the mypy config with `mypy --config-file mypy.ini`?

**Comment by revmischa** [comment]
Turned out my pre-commit action was missing the deps

**Comment by nrbnlulu** [comment]
tackled me as well:
```console
pyproject.toml:1: error: Error importing plugin "mypy_django_plugin.main": No module named 'mypy_django_plugin'
```
using Poetry 
```toml

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "tserver.tzv5hob.settings"

[tool.poetry.dev-dependencies]
django-stubs = {extras = ["compatible-mypy"], version = "^1.12.0"}
```
and pre-commit-hook:
```yaml
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
    - id: mypy
```

**Comment by adamchainz** [comment]
To use django-stubs with the pre-commit mypy mirror, you need to include `django-stubs` in the environment that pre-commit sets up:

```yaml
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
    - id: mypy
      additional_dependencies:
      - django-stubs
```
