### ISSUE TITLE
Configure django-stubs with pyproject.toml

### ISSUE THREAD

**Issue by canassa** [typeddjango/django-stubs#638]
Hello,

The django-stubs README includes an example on how to configure it using the `mypy.ini` or `setup.cfg` files:

```
[mypy]
plugins =
    mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = "myproject.settings"
```

But since mypy recently added support for pyproject.toml files I think that it would be nice to include a pyproject.toml example too.

**Comment by canassa** [comment]
Edit: I wrongly assumed that the plugins configurations were handled by mypy itself and not implemented in the plugins themselves. But I just noticed that the [extract_django_settings_module](https://github.com/typeddjango/django-stubs/blob/47f1700a8b1f5d0ec279ebaf27fd59c84254d1ff/mypy_django_plugin/main.py#L55) is parsing the pyproject.toml file as a config file and not as TOML file.

I believe that django-stubs itself has to be updated in order to handle both .cfg/.ini files or .toml files. Is that correct?

**Comment by sobolevn** [comment]
I think so, yes. 

PRs are welcome (in case it won't make our config-code way too complex).

**Comment by graingert** [comment]
a note, according to the the pyproject.toml spec django-stubs should look in

```toml
[tool.django-stubs]
settings_module = "some.settings.module"
```

and not for example:

```toml
[tool.mypy.plugins.django-stubs]
settings_module = "some.settings.module"
```
